@startuml Entity Relationship Diagrams
entity "access_grants" {
  * id : int <<PK>>
  --
  * dataset_id : int <<FK>>
  * owner_id : int <<FK>>
  * grant_level : nvarchar(255)
  * access_type : nvarchar(255)
  requestor_id : int <<FK>>
  is_project_description_required : bit
  created_at : datetime2(0)
  updated_at : datetime2(0)
  deleted_at : datetime2(0)
}

entity "datasets" {
  * id : int <<PK>>
  --
  * owner_id : int <<FK>>
  * creator_id : int <<FK>>
  * slug : nvarchar(255)
  * name : nvarchar(255)
  * description : nvarchar(MAX)
  subscription_url : nvarchar(1000)
  subscription_access_code : nvarchar(255)
  is_subscribable : bit
  is_spatial_data : bit
  is_live_data : bit
  terms_of_use : nvarchar(MAX)
  credits : nvarchar(MAX)
  owner_notes : nvarchar(MAX)
  status : nvarchar(100)
  error_code : nvarchar(100)
  error_details : nvarchar(MAX)
  published_at : datetime2(0)
  deactivated_at : datetime2(0)
  created_at : datetime2(0)
  updated_at : datetime2(0)
  deleted_at : datetime2(0)
}

entity "roles" {
  * id : int <<PK>>
  --
  * user_id : int <<FK>>
  * role : nvarchar(100)
  created_at : datetime2(0)
  updated_at : datetime2(0)
  deleted_at : datetime2(0)
}

entity "stewardship_evolutions" {
  * id : int <<PK>>
  --
  * dataset_id : int <<FK>>
  * owner_id : int <<FK>>
  * support_id : int <<FK>>
  * owner_name : nvarchar(100)
  * owner_position : nvarchar(255)
  * support_name : nvarchar(100)
  * support_email : nvarchar(100)
  * support_position : nvarchar(255)
  department : nvarchar(255)
  division : nvarchar(255)
  branch : nvarchar(255)
  unit : nvarchar(255)
  created_at : datetime2(0)
  updated_at : datetime2(0)
  deleted_at : datetime2(0)
}

entity "tags" {
  * id : int <<PK>>
  --
  * name : nvarchar(255)
  created_at : datetime2(0)
  updated_at : datetime2(0)
  deleted_at : datetime2(0)
}

entity "taggings" {
  * id : int <<PK>>
  --
  * tag_id : int <<FK>>
  * taggable_id : int - foreign key
  * taggable_type : nvarchar(255)
  created_at : datetime2(0)
  updated_at : datetime2(0)
  deleted_at : datetime2(0)
}

entity "users" {
  * id : int <<PK>>
  --
  * email : nvarchar(100)
  * auth0_subject : nvarchar(100)
  first_name : nvarchar(100)
  last_name : nvarchar(100)
  position : nvarchar(100)
  department : nvarchar(100)
  division : nvarchar(100)
  branch : nvarchar(100)
  unit : nvarchar(100)
  last_employee_directory_sync_at: datetime2(0)
  created_at : datetime2(0)
  updated_at : datetime2(0)
  deleted_at : datetime2(0)
}

entity "user_groups" {
  * id : int <<PK>>
  --
  * parent_id : int <<FK>>
  name: nvarchar(255)
  type: nvarchar(255)
  order: number
  last_division_directory_sync_at: datetime2(0)
  created_at : datetime2(0)
  updated_at : datetime2(0)
  deleted_at : datetime2(0)
}

entity "user_group_memberships" {
  * id : int <<PK>>
  --
  * userId : int <<FK>>
  * department_id : int <<FK>>
  division_id : int <<FK>>
  branch_id : int <<FK>>
  unit_id : int <<FK>>
  created_at : datetime2(0)
  updated_at : datetime2(0)
  deleted_at : datetime2(0)
}

' Define relationships
users }o--|| roles : user_id
users }o--|| datasets : owner_id
users }o--|| datasets : creator_id
datasets }o--|| stewardship_evolutions : dataset_id
users }o--|| stewardship_evolutions : owner_id
users }o--|| stewardship_evolutions : support_id
users |o--|| user_group_memberships : user_id
user_groups }o--|| user_group_memberships : department_id
user_groups }o--|| user_group_memberships : division_id
user_groups }o--|| user_group_memberships : branch_id
user_groups }o--|| user_group_memberships : unit_id
datasets }o--|| taggings : taggable_id, tagging_type
taggings ||--o{ tags : tag_id
datasets }o--|| access_grants : dataset_id
users }o--|| access_grants : owner_id
users }o--|| access_grants : requestor_id
@enduml
