@startuml Entity Relationship Diagrams
entity "access_grants" {
  * id : int <<PK>>
  --
  * dataset_id : int <<FK>>
  * grant_level : nvarchar(255)
  * access_type : nvarchar(255)
  creator_id : int <<FK>>
  support_id : int <<FK>>
  is_project_description_required : bit
  created_at : datetime2(0)
  updated_at : datetime2(0)
  deleted_at : datetime2(0)
}

entity "access_requests" {
  * id : int <<PK>>
  --
  * dataset_id : int <<FK>>
  * access_grant_id : int <<FK>>
  * requestor_id : int <<FK>>
  * access_code : nvarchar(255)
  denier_id : int <<FK>>
  approver_id : int <<FK>>
  revoker_id : int <<FK>>
  project_name: nvarchar(255)
  project_description: nvarchar(MAX)
  approved_at : datetime2(0)
  denied_at : datetime2(0)
  revoked_at : datetime2(0)
  denial_reason: nvarchar(MAX)
  created_at : datetime2(0)
  updated_at : datetime2(0)
  deleted_at : datetime2(0)
}

entity "dataset_fields" {
  * id : int <<PK>>
  --
  * dataset_id : int <<FK>>
  * name : nvarchar(255)
  * display_name : nvarchar(255)
  * data_type : nvarchar(100)
  description : nvarchar(1000)
  note : nvarchar(MAX)
  is_excluded_from_preview : bit
  created_at : datetime2(0)
  updated_at : datetime2(0)
  deleted_at : datetime2(0)
}

entity "dataset_integrations" {
  * id : int <<PK>>
  --
  * dataset_id : int <<FK>>
  * url : nvarchar(1024)
  header_key : nvarchar(1024)
  header_value : nvarchar(4000)
  jmes_path_transform : nvarchar(1024)
  raw_json_data : nvarchar(MAX)
  parsed_json_data : nvarchar(MAX)
  status : nvarchar(100)
  error_code : nvarchar(100)
  error_details : nvarchar(MAX)
  estimated_size_in_bytes : int
  estimated_number_of_records : int
  estimated_response_time_in_ms : int
  last_success_at : datetime2(0)
  last_failure_at : datetime2(0)
  created_at : datetime2(0)
  updated_at : datetime2(0)
  deleted_at : datetime2(0)
}

entity "dataset_stewardships" {
  * id : int <<PK>>
  --
  * dataset_id : int <<FK>>
  * owner_id : int <<FK>>
  * support_id : int <<FK>>
  * department : int <<FK>>
  division_id : int <<FK>>
  branch_id : int <<FK>>
  unit_id : int <<FK>>
  created_at : datetime2(0)
  updated_at : datetime2(0)
  deleted_at : datetime2(0)
}

entity "datasets" {
  * id : int <<PK>>
  --
  * owner_id : int <<FK>>
  * creator_id : int <<FK>>
  * slug : nvarchar(255)
  * name : nvarchar(255)
  * description : nvarchar(MAX)
  is_spatial_data : bit
  is_live_data : bit
  terms_of_use : nvarchar(MAX)
  credits : nvarchar(MAX)
  owner_notes : nvarchar(MAX)
  published_at : datetime2(0)
  deactivated_at : datetime2(0)
  created_at : datetime2(0)
  updated_at : datetime2(0)
  deleted_at : datetime2(0)
}

entity "roles" {
  * id : int <<PK>>
  --
  * user_id : int <<FK>>
  * role : nvarchar(100)
  created_at : datetime2(0)
  updated_at : datetime2(0)
  deleted_at : datetime2(0)
}

entity "taggings" {
  * id : int <<PK>>
  --
  * tag_id : int <<FK>>
  * taggable_id : int - foreign key
  * taggable_type : nvarchar(255)
  created_at : datetime2(0)
  updated_at : datetime2(0)
  deleted_at : datetime2(0)
}

entity "tags" {
  * id : int <<PK>>
  --
  * name : nvarchar(255)
  created_at : datetime2(0)
  updated_at : datetime2(0)
  deleted_at : datetime2(0)
}


entity "user_group_memberships" {
  * id : int <<PK>>
  --
  * user_id : int <<FK>>
  * department_id : int <<FK>>
  division_id : int <<FK>>
  branch_id : int <<FK>>
  unit_id : int <<FK>>
  created_at : datetime2(0)
  updated_at : datetime2(0)
  deleted_at : datetime2(0)
}

entity "user_groups" {
  * id : int <<PK>>
  --
  * parent_id : int <<FK>>
  name: nvarchar(255)
  type: nvarchar(255)
  order: number
  last_division_directory_sync_at: datetime2(0)
  created_at : datetime2(0)
  updated_at : datetime2(0)
  deleted_at : datetime2(0)
}

entity "users" {
  * id : int <<PK>>
  --
  * email : nvarchar(100)
  * auth0_subject : nvarchar(100)
  first_name : nvarchar(100)
  last_name : nvarchar(100)
  position : nvarchar(100)
  department : nvarchar(100)
  division : nvarchar(100)
  branch : nvarchar(100)
  unit : nvarchar(100)
  last_sync_success_at: datetime2(0)
  last_sync_failure_at: datetime2(0)
  created_at : datetime2(0)
  updated_at : datetime2(0)
  deleted_at : datetime2(0)
}

entity "visualization_controls" {
  * id : int <<PK>>
  --
  * dataset_id : int <<FK>>
  is_downloadable_as_csv : bit
  has_preview_row_limit : bit
  preview_row_limit : int
  has_preview : bit
  has_fields_excluded_from_preview : bit
  created_at : datetime2(0)
  updated_at : datetime2(0)
  deleted_at : datetime2(0)
}

' Define relationships
access_grants }o--|| access_requests : access_grant_id
datasets }o--|| access_grants : dataset_id
datasets }o--|| dataset_fields : dataset_id
datasets }o--|| dataset_integrations : dataset_id
datasets }o--|| taggings : taggable_id, tagging_type = 'Dataset'
datasets |o--|| dataset_stewardships : dataset_id
datasets }o--|| access_requests : dataset_id
datasets }o--|| visualization_controls : dataset_id
taggings ||--o{ tags : tag_id
user_groups }o--|| dataset_stewardships : branch_id
user_groups }o--|| dataset_stewardships : department_id
user_groups }o--|| dataset_stewardships : division_id
user_groups }o--|| dataset_stewardships : unit_id
user_groups }o--|| user_group_memberships : branch_id
user_groups }o--|| user_group_memberships : department_id
user_groups }o--|| user_group_memberships : division_id
user_groups }o--|| user_group_memberships : unit_id
users }o--|| access_grants : support_id
users }o--|| access_grants : creator_id
users }o--|| access_requests : requestor_id
users }o--|| access_requests : denier_id
users }o--|| access_requests : approver_id
users }o--|| access_requests : revoker_id
users }o--|| dataset_stewardships : owner_id
users }o--|| dataset_stewardships : support_id
users }o--|| datasets : creator_id
users }o--|| datasets : owner_id
users }o--|| roles : user_id
users |o--|| user_group_memberships : user_id
@enduml
